

esportes = [
    {
        "id": 1,
        "nome": "Futsal",
        "participantes_max_por_time": 10,
        "participantes_min_por_time": 5,
        "modalidade": "masculino ou feminino",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "futsal.jpg",
    },
    {
        "id": 2,
        "nome": "Vôlei",
        "participantes_max_por_time": 12,
        "participantes_min_por_time": 5,
        "modalidade": "mista",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "Volei.jpg",
    },
    {
        "id": 3,
        "nome": "Basquete",
        "participantes_max_por_time": 10,
        "participantes_min_por_time": 5,
        "modalidade": "masculino ou feminino",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "basquete.jpg",
    },
    {
        "id": 4,
        "nome": "Handebol",
        "participantes_max_por_time": 8,
        "participantes_min_por_time": 5,
        "modalidade": "mista",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "handbol.jpg",
    },
    {
        "id": 5,
        "nome": "Queimada",
        "participantes_max_por_time": 6,
        "participantes_min_por_time": 5,
        "modalidade": "mista",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "queimada.jpg",
    },
    {
        "id": 6,
        "nome": "Tênis de Mesa",
        "participantes_max_por_time": 1,
        "participantes_min_por_time": 5,
        "modalidade": "masculino ou feminino",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "tenismesa.jpg",
    },
    {
        "id": 7,
        "nome": "Badminton",
        "participantes_max_por_time": 2,
        "participantes_min_por_time": 5,
        "modalidade": "mista",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "badminton.jpg",
    },
    {
        "id": 8,
        "nome": "Futebol de Campo",
        "participantes_max_por_time": 11,
        "participantes_min_por_time": 5,
        "modalidade": "masculino ou feminino",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "futebol.jpg",
    },
    {
        "id": 9,
        "nome": "Ginástica Artística",
        "participantes_max_por_time": 1,
        "participantes_min_por_time": 5,
        "modalidade": "masculino ou feminino",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "ginastica.jpg",
    },
    {
        "id": 10,
        "nome": "Futevolei",
        "participantes_max_por_time": 5,
        "participantes_min_por_time": 5,
        "modalidade": "masculino ou feminino",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "futvolei.jpg",
    },
    {
        "id": 11,
        "nome": "Vôlei de Praia",
        "participantes_max_por_time": 2,
        "participantes_min_por_time": 5,
        "modalidade": "mista",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "voleipraia.jpg",
    },
    {
        "id": 12,
        "nome": "Capoeira",
        "participantes_max_por_time": 1,
        "participantes_min_por_time": 5,
        "modalidade": "masculino ou feminino",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "capoeira.jpg",
    },
    {
        "id": 13,
        "nome": "Futebol para Cegos",
        "participantes_max_por_time": 3,
        "participantes_min_por_time": 5,
        "modalidade": "misto",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "futcego.jpg",
    },
    {
        "id": 14,
        "nome": "Futmesa",
        "participantes_max_por_time": 2,
        "participantes_min_por_time": 5,
        "modalidade": "misto",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "futmesa.jpg",
    },
    {
        "id": 15,
        "nome": "Altinha",
        "participantes_max_por_time": 1,
        "participantes_min_por_time": 5,
        "modalidade": "misto",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "altinha.jpg",
    },
    {
        "id": 16,
        "nome": "Frisbee",
        "participantes_max_por_time": 7,
        "participantes_min_por_time": 5,
        "modalidade": "misto",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "frisbee.jpg",
    },
    {
        "id": 17,
        "nome": "Xadrez",
        "participantes_max_por_time": 1,
        "participantes_min_por_time": 5,
        "modalidade": "misto",
        "detalhes": "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "foto": "xadrez.jpg",       
    },
]